### ISSUE TITLE
Integrate Unify into Promptflow

### ISSUE THREAD

**Issue by paras55** [unifyai/unify#23]
## Description

This issue tracks the process of facilitating this integration and ensures our repository is ready for incorporation into Promptflow.

## Objectives

- [ ] Evaluate the compatibility of Unify with Promptflow
- [ ] Identify any potential conflicts or dependencies
- [ ] Determine the best method for integration (e.g., submodule, direct code import, package dependency)
- [ ] Create a plan for the integration process
- [ ] Implement the integration
- [ ] Update documentation to reflect the new integrated features
- [ ] Ensure all tests pass after integration
- [ ] Review and update CI/CD pipeline if necessary
- [ ] Create examples/demos highlighting new capabilities of Promptflow

## Resources

- Promptflow GitHub: [https://github.com/microsoft/promptflow](https://github.com/microsoft/promptflow)
- Relevant documentation: [https://microsoft.github.io/promptflow/](https://microsoft.github.io/promptflow/)
- Team members to consult: @iamjameskeane @paras55

**Comment by KatoStevenMubiru** [comment]
Hi team,

I'll be leading the effort on integrating Unify into Promptflow. I'm starting with the compatibility evaluation and will update this issue as we progress through the objectives.

@iamjameskeane @paras55 - Please feel free to chime in with any insights or concerns as we move forward.

**Comment by KatoStevenMubiru** [comment]
Current Progress:
Compatibility Evaluation: Completed. Minor issues identified, awaiting resolution strategies.
Integration Method: Decided on package dependency for efficiency and compatibility.
Next Steps:
Integration Plan: Finalize and share the detailed plan by end of day, Friday, July 19.
Implementation Start: Begin coding on Tuesday, July 23, post-plan approval.
Documentation Update & Testing: Start parallel to implementation to ensure seamless integration.
Immediate Support Needed:
Assistance with resolving minor compatibility issues.
Clarifications on certain Unify functionalities for optimal integration.
For Monday's Meeting:
Review and finalize the integration plan.
Discuss and assign roles for implementation tasks.

**Comment by KatoStevenMubiru** [comment]
Current state of the plan , Follow this link : [Discussion with PromptFlow team](`https://github.com/microsoft/promptflow/issues/3560`)
